# Generated by Django 6.0.4 on 2026-04-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('viewer', 'Viewer'), ('manager', 'Manager')], default='viewer', max_length=20),
        ),
    ]
