# Generated by Django 6.0.4 on 2026-05-14 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 14, 14, 37, 35, 588692)),
        ),
    ]
